apiVersion: v1
kind: Service
metadata:
  name: ajktown-consistency-svc
  namespace: ajktown
  labels:
    app: ajktown-consistency
spec:
  selector:
    app: ajktown-consistency
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort